### ISSUE TITLE
Could you replace by 'read' from a buffer

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/isotherm-analysis#26]
The library does not have file system access especially in the browser

https://github.com/cheminfo/isotherm-analysis/blob/3baecbbb072fb088c6301efa1f997cc106b730bf/src/from/fromBelsorp.js#L112-L114

**Comment by kjappelbaum** [comment]
hm ... i thought i already fixed those cases. Thanks for finding this one, too.
