### ISSUE TITLE
Size of xlsx ??

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/isotherm-analysis#27]
The build version of the package:
```
-rw-r--r--   1 lpatiny  staff  1847285 Oct 13 07:50 isotherm-analysis.js
```

If I comment this export:
// export { fromBelsorp } from './from/fromBelsorp';
```
-rw-r--r--   1 lpatiny  staff  358875 Oct 13 07:55 isotherm-analysis.js
```

Is it really related to xlsx ?

**Comment by kjappelbaum** [comment]
https://github.com/SheetJS/sheetjs/issues/1640

i can look into using the mini build.

**Comment by kjappelbaum** [comment]
Hm ...

i didn't get 

```
 alias({
        entries: [{ find: './dist/cpexcel.js', replacement: '' }],
      }),
```

to work

**Comment by kjappelbaum** [comment]
also, looking at this we cannot exclude this apparently because according to https://github.com/SheetJS/sheetjs/issues/438#issuecomment-286000026 it is needed for xls, which we need to read.

**Comment by lpatiny** [comment]
Thanks for investigation. Indeed we can do nothing about it but at least we know where it is coming from.
