### ISSUE TITLE
implement the files from ENS

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/isotherm-analysis#6]

**Comment by kjappelbaum** [comment]
they create SMP files ... https://www.micromeritics.com/product-showcase/MicroActive-Interactive-Data-Analysis-Software/MicroActive-Interactive-Data-Analysis-Reports.aspx

**Comment by kjappelbaum** [comment]
3FLEX and 3Star to measure isotherms (Micromeritics Instruments).

**Comment by kjappelbaum** [comment]
Could not figure out how to read this filetype. Example here https://www.dropbox.com/s/qh2qn70tcwntzg9/SN_45-MIL-160%28Al%29-2.SMP?dl=0.

Since they seem to be able to also save csv it does not seem to be a priority

**Comment by kjappelbaum** [comment]
@lpatiny do you have an idea how we could read this SMP file? If not, I think we can just close this issue and go with the csv

**Comment by lpatiny** [comment]
Never saw a description of this format. It is a binary file and in case we find the description we can use the library `iobuffer` (https://www.npmjs.com/package/iobuffer) that allows to easily manipulate binary files and that we use in all our binary parsers.

**Comment by kjappelbaum** [comment]
ok, thanks then I'll close and just ask them to export in some other way because I have no description of the file.
